config/routes.rb
Rails.application.routes.draw do
  get 'people/index'
  get 'people/show'
  get 'people/new'
  get 'people/edit'
  get 'people/index'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'people#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :update, :edit]

  def index
    @people = Person.all
  end

  def show
    #Person.find()
    #SELECT * PERSON WHERE ID 
    # renders the show page in the view
  end

  def new
    @person = Person.new
    render partial: "form"
  end

  # post to create in the db
  def create
    @person = Person.create(person_params)
    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
    # render the edit form
    render partial: "form"
  end

  def update
    if @person.update(person_params)
      redirect_to @person
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to root_path
  end

  private
    def person_params
      params.require(:person).permit(:name, :hair_color, :eye_color, :gender, :alive, :age)
    end

    def set_person
      @person = Person.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModelAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<h1><%= @person.id ? 'Edit Contact' : 'Create Contact' %></h1>

<%= form_for @person do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.label :hair_color%>  
  <%= f.text_field :hair_color %>
  <%= f.label :eye_color%>  
  <%= f.text_field :eye_color %>
  <%= f.label :gender %>
  <%= f.select :gender, [ 'Male', 'Female', 'Other', 'N/A' ], :prompt => 'Select One' %>
  <%= f.label :alive %>
  <%= f.radio_button :alive, :checked => true %>
  <%= f.submit %>
<% end %>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>People</h1>

<%= link_to 'Create New Contact', new_person_path %>
<br>
<br>
<% @people.each do |person| %>
  <%= link_to person.name, person %>
<% end %>

app/views/people/new.html.erb
<h1>People#new</h1>
<p>Find me in app/views/people/new.html.erb</p>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
Age: <%= @person.age %><br>
Hair Color: <%= @person.hair_color %><br>
Eye Color: <%= @person.eye_color %><br>
Gender: <%= @person.gender %><br>
Alive: <%= @person.alive %><br>
<br><br>
<%= link_to 'Edit Person', edit_person_path(@person) %>
<%= link_to 'Delete Person', @person, method: :delete %>
<%= link_to 'Home', root_path %>